//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductPractic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furniture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Furniture()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int ID_Furniture { get; set; }
        public string FurnitureName { get; set; }
        public int AmountStore { get; set; }
        public double PriceInRUB { get; set; }
        public int Material_ID { get; set; }
        public int Style_ID { get; set; }
        public int Size_ID { get; set; }
        public int Colour_ID { get; set; }
        public int Provider_ID { get; set; }
    
        public virtual Colours Colours { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual Providers Providers { get; set; }
        public virtual Size Size { get; set; }
        public virtual Styles Styles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
