//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductPractic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductPractic5Entities : DbContext
    {
        public ProductPractic5Entities()
            : base("name=ProductPractic5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Colours> Colours { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Furniture> Furniture { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Providers> Providers { get; set; }
        public virtual DbSet<Role1> Role1 { get; set; }
        public virtual DbSet<Size> Size { get; set; }
        public virtual DbSet<Styles> Styles { get; set; }
    }
}
