//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductPractic
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int ID_OrderDetails { get; set; }
        public int Furniture_ID { get; set; }
        public int Order_ID { get; set; }
    
        public virtual Furniture Furniture { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
